# Generated by Django 6.0.2 on 2026-02-07 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=99)),
                ('email', models.CharField(max_length=99)),
                ('phone_number', models.CharField(max_length=99)),
                ('specialization', models.CharField(max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patients_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=99)),
                ('email', models.CharField(max_length=99)),
                ('phone_number', models.CharField(max_length=99)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('app_date', models.DateField()),
                ('status', models.CharField(max_length=99)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.patient')),
            ],
        ),
    ]
